module.exports = [
  {
    id: 1,
    name: "Darcy Holmes",
    location: "Ottawa",
    cuisine: "Italian and French",
    rating: 4.8,
    bio: "Cooking does not need any instructions or rules.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-01.jpg",
  },
  {
    id: 2,
    name: "Jacob Lawrence",
    location: "Calgary",
    cuisine: "French and Spanish",
    rating: 5.0,
    bio: "With our cooking skills we can tell an entertaining story.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-02.jpg",
  },
  {
    id: 3,
    name: "Dwight Nelson",
    location: "Muskoka",
    cuisine: "Greek and Middle Eastern",
    rating: 4.5,
    bio: "A happy stomach can conquer the entire world.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-03.jpg",
  },
  {
    id: 4,
    name: "Lani Cortez",
    location: "Vancouver",
    cuisine: "Mexican and French",
    rating: 4.1,
    bio: "A chef doesn’t have a proper roadmap to walk on the path of being a great cook.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-04.jpg",
  },
  {
    id: 5,
    name: "Mercy Woodcock",
    location: "Toronto",
    cuisine: "Indian and Thai",
    rating: 4.0,
    bio: "Always try to cook good food with fresh ingredients.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-05.jpg",
  },
  {
    id: 6,
    name: "Armaan Campbell",
    location: "Ottawa",
    cuisine: "Spanish and French",
    rating: 3.2,
    bio: "Cutting – chopping – sauté – fry – –I am in love with these!",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-06.jpg",
  },
  {
    id: 7,
    name: "Thiago Orozco",
    location: "Calgary",
    cuisine: "Greek and Italian",
    rating: 3.8,
    bio: "Cooking is a great art that requires taste and also proper measurements.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-07.jpg",
  },
  {
    id: 8,
    name: "Baxter Pitt",
    location: "Muskoka",
    cuisine: "Thai and Indian",
    rating: 4.4,
    bio: "ur great cooking comes from the special inspiration from many simple things around us.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-08.jpg",
  },
  {
    id: 9,
    name: "George Jaques",
    location: "Vancouver",
    cuisine: "Lebanese and Greek",
    rating: 4.9,
    bio: "I can take care of your empty stomach.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-09.jpg",
  },
  {
    id: 10,
    name: "Paisley Underwood",
    location: "Toronto",
    cuisine: "Spanish and French",
    rating: 4.1,
    bio: "I am proud to be a chef. I bring happiness to your stomach.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-10.jpg",
  },
  {
    id: 11,
    name: "Robert Cardamon",
    location: "Ottawa",
    cuisine: "French and Italian",
    rating: 3.5,
    bio: "Chefs believe that their original target is taking care of others.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-11.jpg",
  },
  {
    id: 12,
    name: "Lucio James",
    location: "Calgary",
    cuisine: "Italian and French",
    rating: 4.5,
    bio: "Good food is the best gift we can offer.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-12.jpg",
  },
  {
    id: 13,
    name: "Georgina Palmer",
    location: "Muskoka",
    cuisine: "French and Italian",
    rating: 4.5,
    bio: "We don’t talk ,we always let our food do the talking about our talent.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-01.jpg",
  },
  {
    id: 14,
    name: "Luka Chapman",
    location: "Vancouver",
    cuisine: "Indian and Greek",
    rating: 4.7,
    bio: "A happy stomach can conquer the entire world.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-14.jpg",
  },
  {
    id: 15,
    name: "Javier Roeder",
    location: "Toronto",
    cuisine: "Mexican and Indian",
    rating: 4.5,
    bio: "People are the most necessary ingredient of our life, without it, we can’t even think about living.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-15.jpg",
  },
  {
    id: 16,
    name: "Carter Prince",
    location: "Ottawa",
    cuisine: "Thai and Greek",
    rating: 3.9,
    bio: "We don’t talk ,we always let our food do the talking about our talent.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-16.jpg",
  },
  {
    id: 17,
    name: "Rachel Ryan",
    location: "Montreal",
    cuisine: "Mexican and Vietnamese",
    rating: 4.8,
    bio: "Chefs know that cooking is not their job but the calling of life.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-17.jpg",
  },
  {
    id: 18,
    name: "Om David",
    location: "Muskoka",
    cuisine: "Greek and Chinese",
    rating: 4.5,
    bio: "We don’t talk ,we always let our food do the talking about our talent.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-18.jpg",
  },
  {
    id: 19,
    name: "Jana Trejo",
    location: "Montreal",
    cuisine: "Spanish and Italian",
    rating: 4.6,
    bio: "Chefs know that cooking is not their job but the calling of life.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-01.jpg",
  },
  {
    id: 20,
    name: "Findlay Simpson",
    location: "Montreal",
    cuisine: "Middle Eastern and Korean",
    rating: 4.5,
    bio: "We can cook what you love.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-17.jpg",
  },
  {
    id: 21,
    name: "Nathan Campbell",
    location: "Ottawa",
    cuisine: "French and Japanese",
    rating: 5.0,
    bio: "Creating the best of cuisines is our primary job.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-09.jpg",
  },
  {
    id: 22,
    name: "Josh Martin",
    location: "Calgary",
    cuisine: "Middle Eastern and Japanese",
    rating: 3.7,
    bio: "I am proud to be a chef ,I bring happiness for your stomach.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-10.jpg",
  },
  {
    id: 23,
    name: "David Chu",
    location: "Muskoka",
    cuisine: "French and Italian",
    rating: 4.7,
    bio: "Cooking is a great art that requires taste and also proper measurements.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-11.jpg",
  },
  {
    id: 24,
    name: "Pamela Warwick",
    location: "Vancouver",
    cuisine: "French and Japanese",
    rating: 4.5,
    bio: "Women chefs are built tougher than anyone else.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-13.jpg",
  },
  {
    id: 25,
    name: "Anna Raval",
    location: "Toronto",
    cuisine: "Thai and Vietnamese",
    rating: 4.5,
    bio: "Cooking is nothing but self expression.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-05.jpg",
  },
  {
    id: 26,
    name: "Ajay Williams",
    location: "Ottawa",
    cuisine: "Spanish and Korean",
    rating: 4.5,
    bio: "A recipe has no soul, you as the cook must bring soul to the recipe. – Thomas Keller",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-02.jpg",
  },
  {
    id: 27,
    name: "Ian Calvert",
    location: "Vancouver",
    cuisine: "Italian and Chinese",
    rating: 3.2,
    bio: "Cooking is love made visible.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-03.jpg",
  },
  {
    id: 28,
    name: "Michael Angelo",
    location: "Calgary",
    cuisine: "Mexican and Italian",
    rating: 4.2,
    bio: "A recipe has no soul. You as the cook must bring soul to the recipe.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-04.jpg",
  },
  {
    id: 29,
    name: "Phill Nuden",
    location: "Muskoka",
    cuisine: "Italian and French",
    rating: 4.5,
    bio: "Chefs believe that their original target is taking care of others.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-09.jpg",
  },
  {
    id: 30,
    name: "Katia Santos",
    location: "Toronto",
    cuisine: "Spanish and Italian",
    rating: 4.5,
    bio: "Boring recipes can make you sad, so always try to make some interesting cuisine.",
    longBio:
      "I was born into an environment where love and respect for food and for healthy produce was one of the pillars of my family education. Even as a child, I spent a lot of time in the kitchen with my mother, while my father, a pioneer in organic farming, began to pass on to me the values of nature.Born in Switzerland and having grown up in Italy, I was 17 when I finished my training at catering school, and I had my first professional experience at Hotel Danieli in Venice. For a year, I had the opportunity of working and of learning alongside the chef Augusto Borghese, enabling me to discover the colours of a refined cuisine.",
    image: "http://localhost:8080/assets/chef-01.jpg",
  },
];
