module.exports = [
  {
    id: 1,
    name: "Nabil Price",
    location: "Ottawa",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 2,
    name: "Arfa Houghton",
    location: "Calgary",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 3,
    name: "Darcy Holmes",
    location: "Muskoka",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 4,
    name: "Lani Cortez",
    location: "Vancouver",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 5,
    name: "Mercy Woodcock",
    location: "Toronto",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 6,
    name: "Armaan Campbell",
    location: "Ottawa",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 7,
    name: "Thiago Orozco",
    location: "Calgary",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 8,
    name: "Georgina Palmer",
    location: "Muskoka",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 9,
    name: "Baxter Pitt",
    location: "Vancouver",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 10,
    name: "Paisley Underwood",
    location: "Toronto",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 11,
    name: "Robert Cardamon",
    location: "Ottawa",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 12,
    name: "Lucio James",
    location: "Calgary",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 13,
    name: "Carter Johns",
    location: "Muskoka",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 14,
    name: "Luka Roeder",
    location: "Vancouver",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 15,
    name: "Katia Santos",
    location: "Toronto",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 16,
    name: "Carter Prince",
    location: "Ottawa",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 17,
    name: "Mateo Hernandez",
    location: "Calgary",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 18,
    name: "Om David",
    location: "Muskoka",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 19,
    name: "Jana Trejo",
    location: "Vancouver",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 20,
    name: "Findlay Simpson",
    location: "Toronto",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 21,
    name: "Nathan Campbell",
    location: "Ottawa",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 22,
    name: "Josh Martin",
    location: "Calgary",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 23,
    name: "David Chu",
    location: "Muskoka",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 24,
    name: "Pamela Warwick",
    location: "Vancouver",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 25,
    name: "Anna Raval",
    location: "Toronto",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 26,
    name: "Ajay Williams",
    location: "Ottawa",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 27,
    name: "Ian Calvert",
    location: "Vancouver",
    rating: 4.5,
    bio: "gsjgsjsgksgks",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 28,
    name: "Michael Angelo",
    location: "Calgary",
    rating: 4.5,
    bio: "We don’t talk – we always let our food do the talking about our talent.",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 29,
    name: "Phill Nuden",
    location: "Muskoka",
    rating: 4.5,
    bio: "We will feel ill if we spend too much time out of the kitchen.",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
  {
    id: 30,
    name: "Katia Santos",
    location: "Toronto",
    rating: 4.5,
    bio: "Boring recipes can make you sad, so always try to make some interesting cuisine.",
    longBio: "shshshsohsohsois",
    image: "shkshkshks",
  },
];
